### ISSUE TITLE
Contribution to jekyll-dash

### ISSUE THREAD

**Issue by bitbrain** [MyCodingSucks/jekyll-dash-without-plugins#1]
Hello @MyCodingSucks!

I just discovered this project of yours and it looks really impressive. Do you think you could raise a pull request to https://github.com/bitbrain/jekyll-dash in order to get rid of the plugins?

Ideally, I don't want to have any plugins either but I introduced them because I didn't know a better way.

**Comment by MyCodingSucks** [comment]
Hello Dear @bitbrain 
Sorry for my late reply. I am a little bit busy recently so I just read it. And thanks for your understanding.

Personally, I want to Pull requests to your repository. And I just need a little time to do it. I know little about git and Github. So I just created a new repository. Also I am learning foreign language in university which means I do not have too much time to learn more about those things. 

(Actually I am no good at programing, so perhaps I need your help in the future.)

**Comment by MyCodingSucks** [comment]
OK, I will try to do it this weekend.
